import { characters } from "slp-parser-js"

export enum ActionState {
	DeadDown,
	DeadLeft,
	DeadRight,
	DeadUp,
	DeadUpStar,
	DeadUpStarIce,
	NA,
	DeadUpFallHitCamera,
	DeadUpFallHitCameraFlat,
	DeadUpFallIce,
	DeadUpFallHitCameraIce,
	Sleep,
	Rebirth,
	RebirthWait,
	Wait,
	WalkSlow,
	WalkMiddle,
	WalkFast,
	Turn,
	TurnRun,
	Dash,
	Run,
	RunDirect,
	RunBrake,
	KneeBend,
	JumpF,
	JumpB,
	JumpAerialF,
	JumpAerialB,
	Fall,
	FallF,
	FallB,
	FallAerial,
	FallAerialF,
	FallAerialB,
	FallSpecial,
	FallSpecialF,
	FallSpecialB,
	DamageFall,
	Squat,
	SquatWait,
	SquatRv,
	Landing,
	LandingFallSpecial,
	Attack11,
	Attack12,
	Attack13,
	Attack100Start,
	Attack100Loop,
	Attack100End,
	AttackDash,
	AttackS3Hi,
	AttackS3HiS,
	AttackS3S,
	AttackS3LwS,
	AttackS3Lw,
	AttackHi3,
	AttackLw3,
	AttackS4Hi,
	AttackS4HiS,
	AttackS4S,
	AttackS4LwS,
	AttackS4Lw,
	AttackHi4,
	AttackLw4,
	AttackAirN,
	AttackAirF,
	AttackAirB,
	AttackAirHi,
	AttackAirLw,
	LandingAirN,
	LandingAirF,
	LandingAirB,
	LandingAirHi,
	LandingAirLw,
	DamageHi1,
	DamageHi2,
	DamageHi3,
	DamageN1,
	DamageN2,
	DamageN3,
	DamageLw1,
	DamageLw2,
	DamageLw3,
	DamageAir1,
	DamageAir2,
	DamageAir3,
	DamageFlyHi,
	DamageFlyN,
	DamageFlyLw,
	DamageFlyTop,
	DamageFlyRoll,
	LightGet,
	HeavyGet,
	LightThrowF,
	LightThrowB,
	LightThrowHi,
	LightThrowLw,
	LightThrowDash,
	LightThrowDrop,
	LightThrowAirF,
	LightThrowAirB,
	LightThrowAirHi,
	LightThrowAirLw,
	HeavyThrowF,
	HeavyThrowB,
	HeavyThrowHi,
	HeavyThrowLw,
	LightThrowF4,
	LightThrowB4,
	LightThrowHi4,
	LightThrowLw4,
	LightThrowAirF4,
	LightThrowAirB4,
	LightThrowAirHi4,
	LightThrowAirLw4,
	HeavyThrowF4,
	HeavyThrowB4,
	HeavyThrowHi4,
	HeavyThrowLw4,
	SwordSwing1,
	SwordSwing3,
	SwordSwing4,
	SwordSwingDash,
	BatSwing1,
	BatSwing3,
	BatSwing4,
	BatSwingDash,
	ParasolSwing1,
	ParasolSwing3,
	ParasolSwing4,
	ParasolSwingDash,
	HarisenSwing1,
	HarisenSwing3,
	HarisenSwing4,
	HarisenSwingDash,
	StarRodSwing1,
	StarRodSwing3,
	StarRodSwing4,
	StarRodSwingDash,
	LipStickSwing1,
	LipStickSwing3,
	LipStickSwing4,
	LipStickSwingDash,
	ItemParasolOpen,
	ItemParasolFall,
	ItemParasolFallSpecial,
	ItemParasolDamageFall,
	LGunShoot,
	LGunShootAir,
	LGunShootEmpty,
	LGunShootAirEmpty,
	FireFlowerShoot,
	FireFlowerShootAir,
	ItemScrew,
	ItemScrewAir,
	DamageScrew,
	DamageScrewAir,
	ItemScopeStart,
	ItemScopeRapid,
	ItemScopeFire,
	ItemScopeEnd,
	ItemScopeAirStart,
	ItemScopeAirRapid,
	ItemScopeAirFire,
	ItemScopeAirEnd,
	ItemScopeStartEmpty,
	ItemScopeRapidEmpty,
	ItemScopeFireEmpty,
	ItemScopeEndEmpty,
	ItemScopeAirStartEmpty,
	ItemScopeAirRapidEmpty,
	ItemScopeAirFireEmpty,
	ItemScopeAirEndEmpty,
	LiftWait,
	LiftWalk1,
	LiftWalk2,
	LiftTurn,
	GuardOn,
	Guard,
	GuardOff,
	GuardSetOff,
	GuardReflect,
	DownBoundU,
	DownWaitU,
	DownDamageU,
	DownStandU,
	DownAttackU,
	DownFowardU,
	DownBackU,
	DownSpotU,
	DownBoundD,
	DownWaitD,
	DownDamageD,
	DownStandD,
	DownAttackD,
	DownFowardD,
	DownBackD,
	DownSpotD,
	Passive,
	PassiveStandF,
	PassiveStandB,
	PassiveWall,
	PassiveWallJump,
	PassiveCeil,
	ShieldBreakFly,
	ShieldBreakFall,
	ShieldBreakDownU,
	ShieldBreakDownD,
	ShieldBreakStandU,
	ShieldBreakStandD,
	FuraFura,
	Catch,
	CatchPull,
	CatchDash,
	CatchDashPull,
	CatchWait,
	CatchAttack,
	CatchCut,
	ThrowF,
	ThrowB,
	ThrowHi,
	ThrowLw,
	CapturePulledHi,
	CaptureWaitHi,
	CaptureDamageHi,
	CapturePulledLw,
	CaptureWaitLw,
	CaptureDamageLw,
	CaptureCut,
	CaptureJump,
	CaptureNeck,
	CaptureFoot,
	EscapeF,
	EscapeB,
	Escape,
	EscapeAir,
	ReboundStop,
	Rebound,
	ThrownF,
	ThrownB,
	ThrownHi,
	ThrownLw,
	ThrownLwWomen,
	Pass,
	Ottotto,
	OttottoWait,
	FlyReflectWall,
	FlyReflectCeil,
	StopWall,
	StopCeil,
	MissFoot,
	CliffCatch,
	CliffWait,
	CliffClimbSlow,
	CliffClimbQuick,
	CliffAttackSlow,
	CliffAttackQuick,
	CliffEscapeSlow,
	CliffEscapeQuick,
	CliffJumpSlow1,
	CliffJumpSlow2,
	CliffJumpQuick1,
	CliffJumpQuick2,
	AppealR,
	AppealL,
	ShoulderedWait,
	ShoulderedWalkSlow,
	ShoulderedWalkMiddle,
	ShoulderedWalkFast,
	ShoulderedTurn,
	ThrownFF,
	ThrownFB,
	ThrownFHi,
	ThrownFLw,
	CaptureCaptain,
	CaptureYoshi,
	YoshiEgg,
	CaptureKoopa,
	CaptureDamageKoopa,
	CaptureWaitKoopa,
	ThrownKoopaF,
	ThrownKoopaB,
	CaptureKoopaAir,
	CaptureDamageKoopaAir,
	CaptureWaitKoopaAir,
	ThrownKoopaAirF,
	ThrownKoopaAirB,
	CaptureKirby,
	CaptureWaitKirby,
	ThrownKirbyStar,
	ThrownCopyStar,
	ThrownKirby,
	BarrelWait,
	Bury,
	BuryWait,
	BuryJump,
	DamageSong,
	DamageSongWait,
	DamageSongRv,
	DamageBind,
	CaptureMewtwo,
	CaptureMewtwoAir,
	ThrownMewtwo,
	ThrownMewtwoAir,
	WarpStarJump,
	WarpStarFall,
	HammerWait,
	HammerWalk,
	HammerTurn,
	HammerKneeBend,
	HammerFall,
	HammerJump,
	HammerLanding,
	KinokoGiantStart,
	KinokoGiantStartAir,
	KinokoGiantEnd,
	KinokoGiantEndAir,
	KinokoSmallStart,
	KinokoSmallStartAir,
	KinokoSmallEnd,
	KinokoSmallEndAir,
	Entry,
	EntryStart,
	EntryEnd,
	DamageIce,
	DamageIceJump,
	CaptureMasterhand,
	CapturedamageMasterhand,
	CapturewaitMasterhand,
	ThrownMasterhand,
	CaptureKirbyYoshi,
	KirbyYoshiEgg,
	CaptureLeadead,
	CaptureLikelike,
	DownReflect,
	CaptureCrazyhand,
	CapturedamageCrazyhand,
	CapturewaitCrazyhand,
	ThrownCrazyhand,
	BarrelCannonWait,
	Wait1,
	Wait2,
	Wait3,
	Wait4,
	WaitItem,
	SquatWait1,
	SquatWait2,
	SquatWaitItem,
	GuardDamage,
	EscapeN,
	AttackS4Hold,
	HeavyWalk1,
	HeavyWalk2,
	ItemHammerWait,
	ItemHammerMove,
	ItemBlind,
	DamageElec,
	FuraSleepStart,
	FuraSleepLoop,
	FuraSleepEnd,
	WallDamage,
	CliffWait1,
	CliffWait2,
	SlipDown,
	Slip,
	SlipTurn,
	SlipDash,
	SlipWait,
	SlipStand,
	SlipAttack,
	SlipEscapeF,
	SlipEscapeB,
	AppealS,
	Zitabata,
	CaptureKoopaHit,
	ThrownKoopaEndF,
	ThrownKoopaEndB,
	CaptureKoopaAirHit,
	ThrownKoopaAirEndF,
	ThrownKoopaAirEndB,
	ThrownKirbyDrinkSShot,
	ThrownKirbySpitSShot
}

type ActionDescriptionType = {
	[action: string]: string
}

export const ActionDescription: ActionDescriptionType = {
	DeadDown: "Standard downward death",
	DeadLeft: "Standard leftward death",
	DeadRight: "Standard rightward death",
	DeadUp: "Upward death",
	DeadUpStar: "Standard Star KO",
	DeadUpStarIce: "Star KO while encased in ice",
	Sleep: "'Nothing' state",
	Rebirth: "Entering on halo",
	RebirthWait: "Waiting on halo",
	Wait: "Standing state",
	KneeBend: "Pre-jump animation",
	JumpF: "First jump forward",
	JumpB: "First jump backward",
	JumpAerialF: "Aerial jump forward",
	JumpAerialB: "Aerial jump backward",
	Fall: "Falling straight down",
	FallF: "Falling with forward DI",
	FallB: "Falling with backward DI",
	FallAerial: "Falling after the second jump",
	FallAerialF: "Falling after the second jump with forward DI",
	FallAerialB: "Falling after the second jump with backward DI",
	FallSpecial: "Special fall after UpB or airdodge",
	FallSpecialF: "Special fall with forward DI",
	FallSpecialB: "Special fall with backward DI",
	DamageFall: "Tumbling",
	Squat: "Going from stand to crouch",
	SquatWait: "Crouching",
	SquatRv: "Going from crouch to stand",
	LandingFallSpecial: "Landing from special fall",
	Attack11: "Jab 1",
	Attack12: "Jab 2",
	Attack13: "Jab 3",
	Attack100Start: "Start of a rapid jab",
	Attack100Loop: "Middle of a rapid jab",
	Attack100End: "End of a rapid jab",
	AttackDash: "Dash attack",
	AttackS3Hi: "High Ftilt",
	AttackS3HiS: "High-mid Ftilt",
	AttackS3S: "Mid Ftilt",
	AttackS3LwS: "Low-mid Ftilt",
	AttackS3Lw: "Low Ftilt",
	AttackHi3: "Uptilt",
	AttackLw3: "Downtilt",
	AttackS4Hi: "High Fsmash",
	AttackS4HiS: "High-mid Fsmash",
	AttackS4S: "Mid Fsmash",
	AttackS4LwS: "Low-mid Fsmash",
	AttackS4Lw: "Low Fsmash",
	AttackHi4: "Upsmash",
	AttackLw4: "Downsmash",
	AttackAirN: "Nair",
	AttackAirF: "Fair",
	AttackAirB: "Bair",
	AttackAirHi: "Uair",
	AttackAirLw: "Dair",
	LandingAirN: "Landing during Nair",
	LandingAirF: "Landing during Fair",
	LandingAirB: "Landing during Bair",
	LandingAirHi: "Landing during Uair",
	LandingAirLw: "Landing during Dair",
	GuardOn: "Shield startup",
	Guard: "Holding shield",
	GuardOff: "Shield release",
	GuardSetOff: "Shield stun",
	DownBoundU: "The missed tech bounce, facing up",
	DownWaitU: "Lying on ground facing up",
	DownDamageU: "Getting hit by a low knockback move lying on ground facing up",
	DownStandU: "Neutral getup",
	DownAttackU: "Get up attack from ground face up",
	DownFowardU: "Missed tech roll forward",
	DownBackU: "Missed tech roll backward",
	DownBoundD: "The missed tech bounce, facing down",
	DownWaitD: "Lying on ground facing down",
	DownDamageD: "Getting hit by a low knockback move lying on the ground facing down",
	DownStandD: "Neutral getup",
	DownAttackD: "Get up attack from ground face down",
	DownFowardD: "Missed tech roll forward",
	DownBackD: "Missed tech roll backward",
	Passive: "Neutral tech",
	PassiveStandF: "Forward tech",
	PassiveStandB: "Backward tech",
	PassiveWall: "Wall tech",
	PassiveWallJump: "Walljump tech/plain walljump",
	PassiveCeil: "Ceiling tech",
	FuraFura: "Shield-break tottering",
	Catch: "Grab",
	CatchPull: "Successfully grabbing a character - pulling them in",
	CatchWait: "Grabbing and holding a character",
	CatchAttack: "Pummel",
	CatchCut: "When opponent breaks of a character's grab",
	ThrowF: "Forward throw",
	ThrowB: "Back throw",
	ThrowHi: "Up throw",
	ThrowLw: "Down throw",
	CapturePulledLw: "Becoming grabbed",
	CaptureWaitLw: "When grabbed",
	CaptureDamageLw: "Pummeled",
	CaptureCut: "Grab release",
	CaptureJump: "Jumping mash out of grab",
	EscapeF: "roll forward",
	EscapeB: "roll backward",
	Escape: "spotdodge",
	EscapeAir: "airdodge",
	ThrownF: "Thrown forward",
	ThrownB: "Thrown backward",
	ThrownHi: "Thrown up",
	ThrownLw: "Thrown down",
	ThrownLwWomen: "Thrown down as a female character",
	Pass: "Drop through platform",
	Ottotto: "Ledge teeter",
	OttottoWait: "",
	FlyReflectWall: "Missed walltech",
	FlyReflectCeil: "Missed ceiling tech",
	StopWall: "Wall bonk",
	StopCeil: "Ceiling bonk",
	MissFoot: "Backward shield slideoff",
	CliffCatch: "Catching the ledge",
	CliffWait: "Hanging on the ledge",
	CliffClimbSlow: "Climbing the ledge (100%+)",
	CliffClimbQuick: "Climbing the ledge (<100%)",
	CliffAttackSlow: "Ledge attack (100%+)",
	CliffAttackQuick: "Ledge attack (<100%)",
	CliffEscapeSlow: "Ledge roll (<100%)",
	CliffEscapeQuick: "Ledge roll (<100%)",
	CliffJumpSlow1: "Ledge jump/tournament winner (100%+)",
	CliffJumpSlow2: "Ledge jump/tournament winner (100%+)",
	CliffJumpQuick1: "Ledge jump/tournament winner (<100%)",
	CliffJumpQuick2: "Ledge jump/tournament winner (<100%)",
	AppealR: "Taunt right",
	AppealL: "Taunt left",
	ShoulderedWait: "DK carry"
}

interface CharacterActionState {
	[frame: number]: string
}

type CharacterMap = {
	[character: number]: CharacterActionState
}

const BowserState: CharacterActionState = {
	341: "Fire Breath Ground Startup",
	342: "Fire Breath Ground Loop",
	343: "Fire Breath Ground End",
	344: "Fire Breath Air Startup",
	345: "Fire Breath Air Loop",
	346: "Fire Breath Air End",
	347: "Koopa Klaw Ground",
	348: "Koopa Klaw Ground Grab",
	349: "Koopa Klaw Ground Pummel",
	350: "Koopa Klaw Ground Wait",
	351: "Koopa Klaw Ground Throw F",
	352: "Koopa Klaw Ground Throw B",
	353: "Koopa Klaw Air",
	354: "Koopa Klaw Air Grab",
	355: "Koopa Klaw Air Pummel",
	356: "Koopa Klaw Air Wait",
	357: "Koopa Klaw Air Throw F",
	358: "Koopa Klaw Air Throw B",
	359: "Whirling Fortress Ground",
	360: "Whirling Fortress Air",
	361: "Bomb Ground Begin",
	362: "Bomb Air",
	363: "Bomb Land"
}

const CptFalconState: CharacterActionState = {
	347: "Falcon Punch Ground",
	348: "Falcon Punch Air",
	349: "Raptor Boost Ground",
	350: "Raptor Boost Ground Hit",
	351: "Raptor Boost Air",
	352: "Raptor Boost Air Hit",
	353: "Falcon Dive Ground",
	354: "Falcon Dive Air",
	355: "Falcon Dive Catch",
	356: "Falcon Dive Ending",
	357: "Falcon Kick Ground",
	358: "Falcon Kick Ground Ending On Ground",
	359: "Falcon Kick Air",
	360: "Falcon Kick Air Ending On Ground",
	361: "Falcon Kick Air Ending In Air",
	362: "Falcon Kick Ground Ending In Air",
	363: "Falcon Kick Hit Wall"
}

const DKState: CharacterActionState = {
	351: "Kong Karry Wait",
	352: "Kong Karry Walk Slow",
	353: "Kong Karry Walk Middle",
	354: "Kong Karry Walk Fast",
	355: "Kong Karry Turn",
	356: "Kong Karry Jump Squat",
	357: "Kong Karry Fall",
	358: "Kong Karry Jump",
	359: "Kong Karry Landing",
	361: "Kong Karry Ground Throw Forward",
	362: "Kong Karry Ground Throw Backward",
	363: "Kong Karry Ground Throw Up",
	364: "Kong Karry Ground Throw Down",
	365: "Kong Karry Air Throw Forward",
	366: "Kong Karry Air Throw Backward",
	367: "Kong Karry Air Throw Up",
	368: "Kong Karry Air Throw Down",
	369: "Giant Punch Ground Charge Startup",
	370: "Giant Punch Ground Charge Loop",
	371: "Giant Punch Ground Charge Stop",
	372: "Giant Punch Ground Early Punch",
	373: "Giant Punch Ground Full Charge Punch",
	374: "Giant Punch Air Charge Startup",
	375: "Giant Punch Air Charge Loop",
	376: "Giant Punch Air Charge Stop",
	377: "Giant Punch Air Early Punch",
	378: "Giant Punch Air Full Charge Punch",
	379: "Headbutt Ground",
	380: "Headbutt Air",
	381: "Spinning Kong Ground",
	382: "Spinning Kong Air",
	383: "Hand Slap Startup",
	384: "Hand Slap Loop",
	385: "Hand Slap End"
}

const DrMarioState: CharacterActionState = {
	341: "Taunt R",
	343: "Megavitamin Ground",
	344: "Megavitamin Air",
	345: "Super Sheet Ground",
	346: "Super Sheet Air",
	347: "Super Jump Punch Ground",
	348: "Super Jump Punch Air",
	349: "Tornado Ground",
	350: "Tornado Air"
}

const SpaciesState: CharacterActionState = {
	341: "Blaster Ground Startup",
	342: "Blaster Ground Loop",
	343: "Blaster Ground End",
	344: "Blaster Air Startup",
	345: "Blaster Air Loop",
	346: "Blaster Air End",
	347: "Phantasm Ground Startup",
	348: "Phantasm Ground",
	349: "Phantasm Ground End",
	350: "Phantasm Startup Air",
	351: "Phantasm Air",
	352: "Phantasm Air End",
	353: "Fire Bird Ground Startup",
	354: "Fire Bird Air Startup",
	355: "Fire Bird Ground",
	356: "Fire Bird Air",
	357: "Fire Bird Ground End",
	358: "Fire Bird Air End",
	359: "Fire Bird Bounce End",
	360: "Reflector Ground Startup",
	361: "Reflector Ground Loop",
	362: "Reflector Ground Reflect",
	363: "Reflector Ground End",
	364: "Reflector Ground Change Direction",
	365: "Reflector Air Startup",
	366: "Reflector Air Loop",
	367: "Reflector Air Reflect",
	368: "Reflector Air End",
	369: "Reflector Air Change Direction",
	370: "Smash Taunt Right Startup",
	371: "Smash Taunt Left Startup",
	372: "Smash Taunt Right Rise",
	373: "Smash Taunt Left Rise",
	374: "Smash Taunt Right Finish",
	375: "Smash Taunt Left Finish"
}

const GanonState: CharacterActionState = {
	347: "Warlock Punch Ground",
	348: "Warlcok Punch Air",
	349: "Gerudo Dragon Ground",
	350: "Gerudo Dragon Ground Hit",
	351: "Gerudo Dragon Air",
	352: "Gerudo Dragon Air Hit",
	353: "Dark Dive Ground",
	354: "Dark Dive Air",
	355: "Dark Dive Catch",
	356: "Dark Dive Ending",
	357: "Wizard's Foot Ground",
	358: "Wizard's Foot Ground Ending On Ground",
	359: "Wizard's Foot Air",
	360: "Wizard's Foot Air Ending On Ground",
	361: "Wizard's Foot Air Ending In Air",
	362: "Wizard's Foot Ground Ending In Air",
	363: "Wizard's Foot Hit Wall"
}

const ICSState: CharacterActionState = {
	341: "Ice Shot Ground",
	342: "Ice Shot Air",
	343: "Popo Squall Hammer Ground Solo",
	344: "Popo Squall Hammer Ground Together",
	345: "Popo Squall Hammer Air Solo",
	346: "Popo Squall Hammer Air Together",
	347: "Popo Belay Ground Startup",
	348: "Popo Belay Ground Catapulting Nana",
	350: "Popo Belay Ground Failed Catapulting",
	351: "Popo Belay Ground Failed Catapulting End",
	352: "Popo Belay Air Startup",
	353: "Popo Belay Air Catapulting Nana",
	354: "Popo Belay Catapulting",
	355: "Popo Belay Air Failed Catapulting",
	356: "Popo Belay Air Failed Catapulting End",
	357: "Blizzard Ground",
	358: "Blizzard Air",
	359: "Nana Squall Hammer Ground Together",
	360: "Nana Squall Hammer Air Together",
	361: "Nana Belay Catapult Startup",
	362: "Nana Belay Ground Catapult End",
	365: "Nana Belay Catapulting"
}

const JigglypuffState: CharacterActionState = {
	341: "Jump 2",
	342: "Jump 3",
	343: "Jump 4",
	344: "Jump 5",
	345: "Jump 6",
	346: "Rollout Ground Start Charge Right",
	347: "Rollout Ground Start Charge Left",
	348: "Rollout Ground Charge Loop",
	349: "Rollout Ground Fully Charged",
	350: "Rollout Ground Charge Release",
	351: "Rollout Ground Start Turn",
	352: "Rollout Ground End Right",
	353: "Rollout Ground End Left",
	354: "Rollout Air Start Charge Right",
	355: "Rollout Air Start Charge Left",
	356: "Rollout Air Charge Loop",
	357: "Rollout Air Fully Charged",
	358: "Rollout Air Charge Release",
	360: "Rollout Air End Right",
	361: "Rollout Air End Left",
	362: "Rollout Hit",
	363: "Pound Ground",
	364: "Pound Air",
	365: "Sing Ground Left",
	366: "Sing Air Left",
	367: "Sing Ground Right",
	368: "Sing Air Right",
	369: "Rest Ground Left",
	370: "Rest Air Left",
	371: "Rest Ground Right",
	372: "Rest Air Right"
}

const KirbyState: CharacterActionState = {
	341: "Jump 2",
	342: "Jump 3",
	343: "Jump 4",
	344: "Jump 5",
	345: "Jump 6"
}

const LinkState: CharacterActionState = {
	341: "Side Smash 2",
	344: "Bow Ground Charge",
	345: "Bow Ground Fully Charged",
	346: "Bow Ground Fire",
	347: "Bow Air Charge",
	348: "Bow Air Fully Charged",
	349: "Bow Air Fire",
	350: "Boomerang Ground Throw",
	351: "Boomerang Ground Catch",
	352: "Boomerang Ground Throw Empty",
	353: "Boomerang Air Throw",
	354: "Boomerang Air Catch",
	355: "Boomerang Air Throw Empty",
	356: "Spin Attack Ground",
	357: "Spin Attack Air",
	358: "Bomb Ground",
	359: "Bomb Air",
	360: "Zair",
	361: "Zair Catch"
}

const YLinkState: CharacterActionState = {
	341: "Side Smash 2",
	342: "Taunt R",
	343: "Taunt L",
	344: "Bow Ground Charge",
	345: "Bow Ground Fully Charged",
	346: "Bow Ground Fire",
	347: "Bow Air Charge",
	348: "Bow Air Fully Charged",
	349: "Bow Air Fire",
	350: "Boomerang Ground Throw",
	351: "Boomerang Ground Catch",
	352: "Boomerang Ground Throw Empty",
	353: "Boomerang Air Throw",
	354: "Boomerang Air Catch",
	355: "Boomerang Air Throw Empty",
	356: "Spin Attack Ground",
	357: "Spin Attack Air",
	358: "Bomb Ground",
	359: "Bomb Air",
	360: "Zair",
	361: "Zair Catch"
}

const LuigiState: CharacterActionState = {
	341: "Fireball Ground",
	342: "Fireball Air",
	343: "Green Missile Ground Startup",
	344: "Green Missile Ground Charge",
	345: "Bow Ground Fully Charged",
	346: "Green Missile Ground Landing",
	347: "Green Missile Ground Takeoff",
	348: "Green Missile Ground Takeoff Misfire",
	349: "Green Missile Air Startup",
	350: "Green Missile Air Charge",
	351: "Green Missile Air",
	352: "Green Missile Air End",
	353: "Green Missile Air Takeoff",
	354: "Green Missile Air Takeoff Misfire",
	355: "Super Jump Punch Ground",
	356: "Super Jump Punch Air",
	357: "Cyclone Ground",
	358: "Cyclone Air"
}

const MarioState: CharacterActionState = {
	343: "Fireball Ground",
	344: "Fireball Air",
	345: "Cape Ground",
	346: "Cape Air",
	347: "Super Jump Punch Ground",
	348: "Super Jump Punch Air",
	349: "Tornado Ground",
	350: "Tornado Air"
}

const MarthState: CharacterActionState = {
	341: "Shield Breaker Ground Start Charge",
	342: "Shield Breaker Ground Charge Loop",
	343: "Shield Breaker Ground Early Release",
	344: "Shield Breaker Ground Fully Charged",
	345: "Shield Breaker Air Start Charge",
	346: "Shield Breaker Air Charge Loop",
	347: "Shield Breaker Air Early Release",
	348: "Shield Breaker Air Fully Charged",
	349: "Dancing Blade 1 Ground",
	350: "Dancing Blade 2 Up Ground",
	351: "Dancing Blade 2 Side Ground",
	352: "Dancing Blade 3 Up Ground",
	353: "Dancing Blade 3 Side Ground",
	354: "Dancing Blade 3 Down Ground",
	355: "Dancing Blade 4 Up Ground",
	356: "Dancing Blade 4 Side Ground",
	357: "Dancing Blade 4 Down Ground",
	358: "Dancing Blade 1 Air",
	359: "Dancing Blade 2 Up Air",
	360: "Dancing Blade 2 Side Air",
	361: "Dancing Blade 3 Up Air",
	362: "Dancing Blade 3 Side Air",
	363: "Dancing Blade 3 Down Air",
	364: "Dancing Blade 4 Up Air",
	365: "Dancing Blade 4 Side Air",
	366: "Dancing Blade 4 Down Air",
	367: "Dolphin Slash Ground",
	368: "Dolphin Slash Air",
	369: "Counter Ground",
	370: "Counter Ground Hit",
	371: "Counter Air",
	372: "Counter Air Hit"
}

const MewtwoState: CharacterActionState = {
	341: "Shadow Ball Ground Start Charge",
	342: "Shadow Ball Ground Charge Loop",
	343: "Shadow Ball Ground Fully Charged",
	344: "Shadow Ball Ground End Charge",
	345: "Shadow Ball Ground Fire",
	346: "Shadow Ball Air Start Charge",
	347: "Shadow Ball Air Charge Loop",
	348: "Shadow Ball Air Fully Charged",
	349: "Shadow Ball Air End Charge",
	350: "Shadow Ball Air Fire",
	351: "Confusion Ground",
	352: "Confusion Air",
	353: "Teleport Ground Startup",
	354: "Teleport Ground Disappear",
	355: "Teleport Ground Reappear",
	356: "Teleport Air Startup",
	357: "Teleport Air Disappear",
	358: "Teleport Air Reappear",
	359: "Disable Ground",
	360: "Disable Air"
}

const RoyState: CharacterActionState = {
	341: "Flare Blade Ground Start Charge",
	342: "Flare Blade Ground Charge Loop",
	343: "Flare Blade Ground Early Release",
	344: "Flare Blade Ground Fully Charged",
	345: "Flare Blade Air Start Charge",
	346: "Flare Blade Air Charge Loop",
	347: "Flare Blade Air Early Release",
	348: "Flare Blade Air Fully Charged",
	349: "Double Edge Dance 1 Ground",
	350: "Double Edge Dance 2 Up Ground",
	351: "Double Edge Dance 2 Side Ground",
	352: "Double Edge Dance 3 Up Ground",
	353: "Double Edge Dance 3 Side Ground",
	354: "Double Edge Dance 3 Down Ground",
	355: "Double Edge Dance 4 Up Ground",
	356: "Double Edge Dance 4 Side Ground",
	357: "Double Edge Dance 4 Down Ground",
	358: "Double Edge Dance 1 Air",
	359: "Double Edge Dance 2 Up Air",
	360: "Double Edge Dance 2 Side Air",
	361: "Double Edge Dance 3 Up Air",
	362: "Double Edge Dance 3 Side Air",
	363: "Double Edge Dance 3 Down Air",
	364: "Double Edge Dance 4 Up Air",
	365: "Double Edge Dance 4 Side Air",
	366: "Double Edge Dance 4 Down Air",
	367: "Blazer Ground",
	368: "Blazer Air",
	369: "Counter Ground",
	370: "Counter Ground Hit",
	371: "Counter Air",
	372: "Counter Air Hit"
}

const SheikState: CharacterActionState = {
	341: "Needle Storm Ground Start Charge",
	342: "Needle Storm Ground Charge Loop",
	343: "Needle Storm Ground End Charge",
	344: "Needle Storm Ground Fire",
	345: "Needle Storm Air Start Charge",
	346: "Needle Storm Air Charge Loop",
	347: "Needle Storm Air End Charge",
	348: "Needle Storm Air Fire",
	349: "Chain Ground Startup",
	350: "Chain Ground Loop",
	351: "Chain Ground End",
	352: "Chain Air Startup",
	353: "Chain Air Loop",
	354: "Chain Air End",
	355: "Vanish Ground Startup",
	356: "Vanish Ground Disappear",
	357: "Vanish Ground Reappear",
	358: "Vanish Air Startup",
	359: "Vanish Air Disappear",
	360: "Vanish Air Reappear",
	361: "Transform Ground",
	362: "Transform Ground Ending",
	363: "Transform Air",
	364: "Transform Air Ending"
}

const GandWState: CharacterActionState = {}

const NessState: CharacterActionState = {}
const PeachState: CharacterActionState = {}
const PikaState: CharacterActionState = {
	341: "Thunder Jolt Ground",
	342: "Thunder Jolt Air",
	343: "Skull Bash Ground Startup",
	344: "Skull Bash Ground Charge",
	346: "Skull Bash Ground Landing",
	347: "Skull Bash Ground Takeoff",
	348: "Skull Bash Air Startup",
	349: "Skull Bash Air Charge",
	350: "Skull Bash Air",
	351: "Skull Bash Air End",
	352: "Skull Bash Air Takeoff",
	353: "Agility Ground Startup",
	354: "Agility Ground",
	355: "Agility Ground End",
	356: "Agility Air Startup",
	357: "Agility Air",
	358: "Agility Air End",
	359: "Thunder Ground Startup",
	360: "Thunder Ground",
	361: "Thunder Ground Hit",
	363: "Thunder Ground End",
	364: "Thunder Air",
	365: "Thunder Air Hit",
	366: "Thunder Air End"
}
const SamusState: CharacterActionState = {
	341: "Bomb Jump Ground",
	342: "Bomb Jump Air",
	343: "Charge Shot Ground Start",
	344: "Charge Shot Ground Loop",
	345: "Charge Shot Ground End",
	346: "Charge Shot Ground Fire",
	347: "Charge Shot Air Start",
	348: "Charge Shot Air Fire",
	349: "Missile Ground",
	350: "Missile Smash Ground",
	351: "Missile Air",
	352: "Missile Smash Air",
	353: "Screw Attack Ground",
	354: "Screw Attack Air",
	355: "Bomb End Ground",
	356: "Bomb Air",
	357: "Zair",
	358: "Zair Catch"
}
const YoshiState: CharacterActionState = {
	341: "Buffered Shield Startup",
	342: "Shield Hold",
	343: "Shield Release",
	344: "Shield Damage",
	345: "Shield Startup",
	346: "Egg Lay Ground",
	347: "Egg Lay Ground Capture Start",
	349: "Egg Lay Ground Capture",
	351: "Egg Lay Air",
	352: "Egg Lay Air Capture Start",
	354: "Egg Lay Air Capture",
	356: "Egg Roll Ground Startup",
	357: "Egg Roll Ground",
	358: "Egg Roll Ground Change Direction",
	359: "Egg Roll Ground End",
	360: "Egg Roll Air Start",
	361: "Egg Roll Air",
	362: "Egg Roll Bounce",
	363: "Egg Roll Air End",
	364: "Egg Throw Ground",
	365: "Egg Throw Air",
	366: "Bomb Ground",
	367: "Bomb Land",
	368: "Bomb Air"
}

const ZeldaState: CharacterActionState = {
	341: "Nayru's Love Ground",
	342: "Nayru's Love Air",
	343: "Din's Fire Ground Startup",
	344: "Din's Fire Ground Travel",
	345: "Din's Fire Ground Explode",
	346: "Din's Fire Air Startup",
	347: "Din's Fire Air Travel",
	348: "Din's Fire Air Explode",
	349: "Farore's Wind Ground",
	350: "Farore's Wind Ground Disappear",
	351: "Farore's Wind Ground Reappear",
	352: "Farore's Wind Air",
	353: "Farore's Wind Air Disappear",
	354: "Farore's Wind Air Reappear",
	355: "Transform Ground",
	356: "Transform Ground Ending",
	357: "Transform Air",
	358: "Transform Air Ending"
}

export const CharacterActionMap: CharacterMap = {
	0: BowserState,
	1: CptFalconState,
	2: DKState,
	3: DrMarioState,
	4: SpaciesState,
	5: SpaciesState,
	6: GanonState,
	7: ICSState,
	8: JigglypuffState,
	9: KirbyState,
	10: LinkState,
	11: LuigiState,
	12: MarioState,
	13: MarthState,
	14: MewtwoState,
	15: GandWState,
	16: NessState,
	17: PeachState,
	18: PikaState,
	19: PikaState,
	20: RoyState,
	21: SamusState,
	22: SheikState,
	23: YoshiState,
	24: YLinkState,
	25: ZeldaState
}
